unique_ids:
  assets:
    standard-page.html: HDGNUQWLHZLLIRILI6F3SE372E66SFPH
    theme.css: Y4TYBCO23NBSY4NXJM3DQ27TJ2ZNAK2B
  forms:
    Form1: T7O5V7EVFRCNQZJB5K4JW4EUJIX3DSPH
  modules: {}
  scripts: {}
  server_modules: {}
